add_subdirectory(sddm)
if(NOT INSTALL_X11_COMPONENTS)
    option(BUILD_ATPOOTB "Build the OOTB (out-of-the-box) wizard" ON)
    if(BUILD_ATPOOTB)
        add_subdirectory(atpootb)
    endif()
    add_subdirectory(shells)
    add_subdirectory(plasmoids)
    add_subdirectory(color_scheme)
    add_subdirectory(desktoptheme)
    add_subdirectory(look-and-feel)
    add_subdirectory(layout-templates)
endif()
